name: 🏭 New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Semver Bump Type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  cut-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn set version stable
          yarn install --immutable

      - name: Bump Version
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        # TODO - https://github.com/microsoft/vscode-vsce/pull/876  
        run: |
          git config --global user.name "OpenGOALBot"
          git config --global user.email "OpenGOALBot@users.noreply.github.com"
          yarn vsce package --no-yarn
          yarn vsce publish ${{ github.event.inputs.bump }} --no-yarn
          git push
          git push origin $(git tag --points-at HEAD)

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
        run: gh release create $(git tag --points-at HEAD) --generate-notes --repo open-goal/opengoal-vscode ./*.vsix
